// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package Msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//服务器消息-----------------------------------------
type ServerOrder int32

const (
	ServerOrder_SERVERORDER_MAP_INIT     ServerOrder = 0
	ServerOrder_SERVERORDER_MAP_UPDATE   ServerOrder = 1
	ServerOrder_SERVERORDER_PLAYER_SET   ServerOrder = 2
	ServerOrder_SERVERORDER_ENEMY_UPDATE ServerOrder = 3
	ServerOrder_SERVERORDER_GAMEOVER     ServerOrder = 4
)

var ServerOrder_name = map[int32]string{
	0: "SERVERORDER_MAP_INIT",
	1: "SERVERORDER_MAP_UPDATE",
	2: "SERVERORDER_PLAYER_SET",
	3: "SERVERORDER_ENEMY_UPDATE",
	4: "SERVERORDER_GAMEOVER",
}

var ServerOrder_value = map[string]int32{
	"SERVERORDER_MAP_INIT":     0,
	"SERVERORDER_MAP_UPDATE":   1,
	"SERVERORDER_PLAYER_SET":   2,
	"SERVERORDER_ENEMY_UPDATE": 3,
	"SERVERORDER_GAMEOVER":     4,
}

func (x ServerOrder) String() string {
	return proto.EnumName(ServerOrder_name, int32(x))
}

func (ServerOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

//客户端消息-----------------------------------------
type ClientOrder int32

const (
	ClientOrder_CLIENTORDER_FOOD_EAT    ClientOrder = 0
	ClientOrder_CLIENTORDER_ENEMY_EAT   ClientOrder = 1
	ClientOrder_CLIENTORDER_DATA_FRAME  ClientOrder = 2
	ClientOrder_CLIENTORDER_SHOOT_SPORE ClientOrder = 3
)

var ClientOrder_name = map[int32]string{
	0: "CLIENTORDER_FOOD_EAT",
	1: "CLIENTORDER_ENEMY_EAT",
	2: "CLIENTORDER_DATA_FRAME",
	3: "CLIENTORDER_SHOOT_SPORE",
}

var ClientOrder_value = map[string]int32{
	"CLIENTORDER_FOOD_EAT":    0,
	"CLIENTORDER_ENEMY_EAT":   1,
	"CLIENTORDER_DATA_FRAME":  2,
	"CLIENTORDER_SHOOT_SPORE": 3,
}

func (x ClientOrder) String() string {
	return proto.EnumName(ClientOrder_name, int32(x))
}

func (ClientOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

type Player struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PosX                 float32  `protobuf:"fixed32,2,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY                 float32  `protobuf:"fixed32,3,opt,name=posY,proto3" json:"posY,omitempty"`
	Bg                   float32  `protobuf:"fixed32,4,opt,name=bg,proto3" json:"bg,omitempty"`
	Size                 float32  `protobuf:"fixed32,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Player) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *Player) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *Player) GetBg() float32 {
	if m != nil {
		return m.Bg
	}
	return 0
}

func (m *Player) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Food struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PosX                 float32  `protobuf:"fixed32,2,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY                 float32  `protobuf:"fixed32,3,opt,name=posY,proto3" json:"posY,omitempty"`
	Bg                   float32  `protobuf:"fixed32,4,opt,name=bg,proto3" json:"bg,omitempty"`
	Size                 float32  `protobuf:"fixed32,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Food) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *Food) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *Food) GetBg() float32 {
	if m != nil {
		return m.Bg
	}
	return 0
}

func (m *Food) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Room struct {
	PLAYER_NUM           int32     `protobuf:"varint,1,opt,name=PLAYER_NUM,json=PLAYERNUM,proto3" json:"PLAYER_NUM,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetPLAYER_NUM() int32 {
	if m != nil {
		return m.PLAYER_NUM
	}
	return 0
}

func (m *Room) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type MapInit struct {
	FOODS_NUM            int32    `protobuf:"varint,1,opt,name=FOODS_NUM,json=FOODSNUM,proto3" json:"FOODS_NUM,omitempty"`
	Food                 []*Food  `protobuf:"bytes,3,rep,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapInit) Reset()         { *m = MapInit{} }
func (m *MapInit) String() string { return proto.CompactTextString(m) }
func (*MapInit) ProtoMessage()    {}
func (*MapInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *MapInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapInit.Unmarshal(m, b)
}
func (m *MapInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapInit.Marshal(b, m, deterministic)
}
func (m *MapInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapInit.Merge(m, src)
}
func (m *MapInit) XXX_Size() int {
	return xxx_messageInfo_MapInit.Size(m)
}
func (m *MapInit) XXX_DiscardUnknown() {
	xxx_messageInfo_MapInit.DiscardUnknown(m)
}

var xxx_messageInfo_MapInit proto.InternalMessageInfo

func (m *MapInit) GetFOODS_NUM() int32 {
	if m != nil {
		return m.FOODS_NUM
	}
	return 0
}

func (m *MapInit) GetFood() []*Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type Update struct {
	FoodId               int32    `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Food                 *Food    `protobuf:"bytes,2,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetFoodId() int32 {
	if m != nil {
		return m.FoodId
	}
	return 0
}

func (m *Update) GetFood() *Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type PlayerSet struct {
	Player               *Player  `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSet) Reset()         { *m = PlayerSet{} }
func (m *PlayerSet) String() string { return proto.CompactTextString(m) }
func (*PlayerSet) ProtoMessage()    {}
func (*PlayerSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *PlayerSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSet.Unmarshal(m, b)
}
func (m *PlayerSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSet.Marshal(b, m, deterministic)
}
func (m *PlayerSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSet.Merge(m, src)
}
func (m *PlayerSet) XXX_Size() int {
	return xxx_messageInfo_PlayerSet.Size(m)
}
func (m *PlayerSet) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSet.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSet proto.InternalMessageInfo

func (m *PlayerSet) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type EnemyUpdata struct {
	ENEMY_NUM            int32     `protobuf:"varint,1,opt,name=ENEMY_NUM,json=ENEMYNUM,proto3" json:"ENEMY_NUM,omitempty"`
	Enemy                []*Player `protobuf:"bytes,2,rep,name=enemy,proto3" json:"enemy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnemyUpdata) Reset()         { *m = EnemyUpdata{} }
func (m *EnemyUpdata) String() string { return proto.CompactTextString(m) }
func (*EnemyUpdata) ProtoMessage()    {}
func (*EnemyUpdata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *EnemyUpdata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnemyUpdata.Unmarshal(m, b)
}
func (m *EnemyUpdata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnemyUpdata.Marshal(b, m, deterministic)
}
func (m *EnemyUpdata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnemyUpdata.Merge(m, src)
}
func (m *EnemyUpdata) XXX_Size() int {
	return xxx_messageInfo_EnemyUpdata.Size(m)
}
func (m *EnemyUpdata) XXX_DiscardUnknown() {
	xxx_messageInfo_EnemyUpdata.DiscardUnknown(m)
}

var xxx_messageInfo_EnemyUpdata proto.InternalMessageInfo

func (m *EnemyUpdata) GetENEMY_NUM() int32 {
	if m != nil {
		return m.ENEMY_NUM
	}
	return 0
}

func (m *EnemyUpdata) GetEnemy() []*Player {
	if m != nil {
		return m.Enemy
	}
	return nil
}

type ServerMessage struct {
	Order                ServerOrder  `protobuf:"varint,1,opt,name=order,proto3,enum=Msg.ServerOrder" json:"order,omitempty"`
	Map                  *MapInit     `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	Update               *Update      `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Playerset            *PlayerSet   `protobuf:"bytes,4,opt,name=playerset,proto3" json:"playerset,omitempty"`
	Enemysmsg            *EnemyUpdata `protobuf:"bytes,5,opt,name=enemysmsg,proto3" json:"enemysmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetOrder() ServerOrder {
	if m != nil {
		return m.Order
	}
	return ServerOrder_SERVERORDER_MAP_INIT
}

func (m *ServerMessage) GetMap() *MapInit {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *ServerMessage) GetUpdate() *Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *ServerMessage) GetPlayerset() *PlayerSet {
	if m != nil {
		return m.Playerset
	}
	return nil
}

func (m *ServerMessage) GetEnemysmsg() *EnemyUpdata {
	if m != nil {
		return m.Enemysmsg
	}
	return nil
}

type EatFoodMsg struct {
	Food                 *Food    `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EatFoodMsg) Reset()         { *m = EatFoodMsg{} }
func (m *EatFoodMsg) String() string { return proto.CompactTextString(m) }
func (*EatFoodMsg) ProtoMessage()    {}
func (*EatFoodMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *EatFoodMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EatFoodMsg.Unmarshal(m, b)
}
func (m *EatFoodMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EatFoodMsg.Marshal(b, m, deterministic)
}
func (m *EatFoodMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EatFoodMsg.Merge(m, src)
}
func (m *EatFoodMsg) XXX_Size() int {
	return xxx_messageInfo_EatFoodMsg.Size(m)
}
func (m *EatFoodMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EatFoodMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EatFoodMsg proto.InternalMessageInfo

func (m *EatFoodMsg) GetFood() *Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type EatEnemyMsg struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EatEnemyMsg) Reset()         { *m = EatEnemyMsg{} }
func (m *EatEnemyMsg) String() string { return proto.CompactTextString(m) }
func (*EatEnemyMsg) ProtoMessage()    {}
func (*EatEnemyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *EatEnemyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EatEnemyMsg.Unmarshal(m, b)
}
func (m *EatEnemyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EatEnemyMsg.Marshal(b, m, deterministic)
}
func (m *EatEnemyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EatEnemyMsg.Merge(m, src)
}
func (m *EatEnemyMsg) XXX_Size() int {
	return xxx_messageInfo_EatEnemyMsg.Size(m)
}
func (m *EatEnemyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EatEnemyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EatEnemyMsg proto.InternalMessageInfo

func (m *EatEnemyMsg) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type ClientDataFrame struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientDataFrame) Reset()         { *m = ClientDataFrame{} }
func (m *ClientDataFrame) String() string { return proto.CompactTextString(m) }
func (*ClientDataFrame) ProtoMessage()    {}
func (*ClientDataFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *ClientDataFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDataFrame.Unmarshal(m, b)
}
func (m *ClientDataFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDataFrame.Marshal(b, m, deterministic)
}
func (m *ClientDataFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDataFrame.Merge(m, src)
}
func (m *ClientDataFrame) XXX_Size() int {
	return xxx_messageInfo_ClientDataFrame.Size(m)
}
func (m *ClientDataFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDataFrame.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDataFrame proto.InternalMessageInfo

func (m *ClientDataFrame) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type ShootSpore struct {
	StartPosx            float32  `protobuf:"fixed32,1,opt,name=start_posx,json=startPosx,proto3" json:"start_posx,omitempty"`
	StartPosy            float32  `protobuf:"fixed32,2,opt,name=start_posy,json=startPosy,proto3" json:"start_posy,omitempty"`
	EndPosx              float32  `protobuf:"fixed32,3,opt,name=end_posx,json=endPosx,proto3" json:"end_posx,omitempty"`
	EndPosy              float32  `protobuf:"fixed32,4,opt,name=end_posy,json=endPosy,proto3" json:"end_posy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShootSpore) Reset()         { *m = ShootSpore{} }
func (m *ShootSpore) String() string { return proto.CompactTextString(m) }
func (*ShootSpore) ProtoMessage()    {}
func (*ShootSpore) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *ShootSpore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShootSpore.Unmarshal(m, b)
}
func (m *ShootSpore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShootSpore.Marshal(b, m, deterministic)
}
func (m *ShootSpore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShootSpore.Merge(m, src)
}
func (m *ShootSpore) XXX_Size() int {
	return xxx_messageInfo_ShootSpore.Size(m)
}
func (m *ShootSpore) XXX_DiscardUnknown() {
	xxx_messageInfo_ShootSpore.DiscardUnknown(m)
}

var xxx_messageInfo_ShootSpore proto.InternalMessageInfo

func (m *ShootSpore) GetStartPosx() float32 {
	if m != nil {
		return m.StartPosx
	}
	return 0
}

func (m *ShootSpore) GetStartPosy() float32 {
	if m != nil {
		return m.StartPosy
	}
	return 0
}

func (m *ShootSpore) GetEndPosx() float32 {
	if m != nil {
		return m.EndPosx
	}
	return 0
}

func (m *ShootSpore) GetEndPosy() float32 {
	if m != nil {
		return m.EndPosy
	}
	return 0
}

type ClientMessage struct {
	Order                ClientOrder      `protobuf:"varint,1,opt,name=order,proto3,enum=Msg.ClientOrder" json:"order,omitempty"`
	Eatfoodmsg           *EatFoodMsg      `protobuf:"bytes,2,opt,name=eatfoodmsg,proto3" json:"eatfoodmsg,omitempty"`
	Eatenemymsg          *EatEnemyMsg     `protobuf:"bytes,3,opt,name=eatenemymsg,proto3" json:"eatenemymsg,omitempty"`
	Clientdataframe      *ClientDataFrame `protobuf:"bytes,4,opt,name=clientdataframe,proto3" json:"clientdataframe,omitempty"`
	Shootspore           *ShootSpore      `protobuf:"bytes,5,opt,name=shootspore,proto3" json:"shootspore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetOrder() ClientOrder {
	if m != nil {
		return m.Order
	}
	return ClientOrder_CLIENTORDER_FOOD_EAT
}

func (m *ClientMessage) GetEatfoodmsg() *EatFoodMsg {
	if m != nil {
		return m.Eatfoodmsg
	}
	return nil
}

func (m *ClientMessage) GetEatenemymsg() *EatEnemyMsg {
	if m != nil {
		return m.Eatenemymsg
	}
	return nil
}

func (m *ClientMessage) GetClientdataframe() *ClientDataFrame {
	if m != nil {
		return m.Clientdataframe
	}
	return nil
}

func (m *ClientMessage) GetShootspore() *ShootSpore {
	if m != nil {
		return m.Shootspore
	}
	return nil
}

func init() {
	proto.RegisterEnum("Msg.ServerOrder", ServerOrder_name, ServerOrder_value)
	proto.RegisterEnum("Msg.ClientOrder", ClientOrder_name, ClientOrder_value)
	proto.RegisterType((*Player)(nil), "Msg.Player")
	proto.RegisterType((*Food)(nil), "Msg.Food")
	proto.RegisterType((*Room)(nil), "Msg.Room")
	proto.RegisterType((*MapInit)(nil), "Msg.MapInit")
	proto.RegisterType((*Update)(nil), "Msg.Update")
	proto.RegisterType((*PlayerSet)(nil), "Msg.PlayerSet")
	proto.RegisterType((*EnemyUpdata)(nil), "Msg.EnemyUpdata")
	proto.RegisterType((*ServerMessage)(nil), "Msg.ServerMessage")
	proto.RegisterType((*EatFoodMsg)(nil), "Msg.EatFoodMsg")
	proto.RegisterType((*EatEnemyMsg)(nil), "Msg.EatEnemyMsg")
	proto.RegisterType((*ClientDataFrame)(nil), "Msg.ClientDataFrame")
	proto.RegisterType((*ShootSpore)(nil), "Msg.ShootSpore")
	proto.RegisterType((*ClientMessage)(nil), "Msg.ClientMessage")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x49, 0x3f, 0x96, 0x1b, 0xb6, 0x55, 0xd6, 0x60, 0xd9, 0xc6, 0xd0, 0x08, 0x02, 0x4d,
	0x03, 0x15, 0x54, 0x24, 0x1e, 0x11, 0xd1, 0xea, 0x42, 0xa5, 0xa5, 0xa9, 0x9c, 0x76, 0xa2, 0x4f,
	0x51, 0x4a, 0xbc, 0x50, 0x69, 0x6d, 0xa2, 0x38, 0xa0, 0x15, 0x5e, 0xf8, 0x03, 0x3c, 0xf3, 0xdf,
	0xf8, 0x35, 0xc8, 0x76, 0x96, 0x7a, 0xd5, 0x40, 0x3c, 0xf0, 0x96, 0xde, 0x73, 0xee, 0xbd, 0xc7,
	0xe7, 0x38, 0x29, 0x98, 0x73, 0x96, 0xb4, 0xb3, 0x3c, 0x2d, 0x52, 0x64, 0x78, 0x2c, 0x71, 0x32,
	0x68, 0x0c, 0x2f, 0xa3, 0x25, 0xcd, 0xd1, 0x3e, 0x6c, 0x64, 0xe2, 0xa9, 0x1f, 0xdb, 0xda, 0x91,
	0x76, 0x5c, 0x27, 0xd5, 0x6f, 0x84, 0xa0, 0x96, 0xa5, 0xec, 0x83, 0xad, 0x1f, 0x69, 0xc7, 0x3a,
	0x11, 0xcf, 0x65, 0x6d, 0x62, 0x1b, 0x55, 0x6d, 0x82, 0xb6, 0x40, 0x9f, 0x26, 0x76, 0x4d, 0x54,
	0xf4, 0x69, 0xc2, 0x39, 0x6c, 0xf6, 0x95, 0xda, 0x75, 0xc9, 0xe1, 0xcf, 0xce, 0x14, 0x6a, 0xbd,
	0x34, 0x8d, 0x39, 0x77, 0x76, 0xbd, 0x49, 0x9f, 0xfd, 0xdf, 0x1d, 0x67, 0x50, 0x23, 0x69, 0x3a,
	0x47, 0x87, 0x00, 0xc3, 0x33, 0x77, 0x82, 0x49, 0x38, 0x18, 0x7b, 0xe5, 0x2e, 0x53, 0x56, 0x06,
	0x63, 0x0f, 0x3d, 0x81, 0xa6, 0x3c, 0x22, 0xb3, 0xf5, 0x23, 0xe3, 0xd8, 0xea, 0x58, 0x6d, 0x8f,
	0x25, 0x6d, 0x69, 0x08, 0xb9, 0xc6, 0x1c, 0x0c, 0x4d, 0x2f, 0xca, 0xfa, 0x8b, 0x59, 0x81, 0x0e,
	0xc0, 0xec, 0xf9, 0x7e, 0x37, 0x50, 0xe6, 0x6d, 0x88, 0x02, 0x1f, 0x77, 0x08, 0xb5, 0x8b, 0x34,
	0x8d, 0x6d, 0x43, 0xcc, 0x32, 0xc5, 0x2c, 0x7e, 0x54, 0x22, 0xca, 0xce, 0x5b, 0x68, 0x8c, 0xb3,
	0x38, 0x2a, 0x28, 0xda, 0x85, 0x26, 0xaf, 0x84, 0xd5, 0xf9, 0x1b, 0xfc, 0x67, 0x3f, 0xae, 0x26,
	0x70, 0x0f, 0x6e, 0x99, 0xf0, 0x12, 0x4c, 0xa9, 0x2d, 0xa0, 0x05, 0x7a, 0x0c, 0x0d, 0x29, 0x50,
	0xb8, 0xb3, 0xa6, 0xbd, 0x84, 0x1c, 0x0f, 0x2c, 0xbc, 0xa0, 0xf3, 0xa5, 0x58, 0x1c, 0x71, 0xf9,
	0x78, 0x80, 0xbd, 0x89, 0x2a, 0x5f, 0x14, 0xb8, 0xfc, 0x47, 0x50, 0xa7, 0x9c, 0x7b, 0x9b, 0x17,
	0x12, 0x71, 0x7e, 0x69, 0xb0, 0x19, 0xd0, 0xfc, 0x0b, 0xcd, 0x3d, 0xca, 0x58, 0x94, 0x50, 0xf4,
	0x14, 0xea, 0x69, 0x1e, 0xd3, 0x5c, 0x4c, 0xdb, 0xea, 0xb4, 0x44, 0x93, 0xa4, 0xf8, 0xbc, 0x4e,
	0x24, 0x8c, 0x1e, 0x82, 0x31, 0x8f, 0xb2, 0xf2, 0x60, 0x77, 0x05, 0xab, 0xf4, 0x94, 0x70, 0x80,
	0x9f, 0xe6, 0xb3, 0x30, 0xe7, 0xc6, 0x69, 0xa4, 0x5f, 0xa4, 0x84, 0xd0, 0x73, 0x30, 0xcb, 0x4c,
	0x68, 0x21, 0x6e, 0x80, 0xd5, 0xd9, 0x52, 0x54, 0x06, 0xb4, 0x20, 0x2b, 0x02, 0x6a, 0x83, 0x29,
	0x54, 0xb3, 0x39, 0x4b, 0xc4, 0xed, 0xb0, 0x4a, 0x79, 0x8a, 0x23, 0x64, 0x45, 0x71, 0x9e, 0x01,
	0xe0, 0xa8, 0xe0, 0x76, 0x7b, 0x2c, 0xa9, 0xa2, 0xd0, 0x6e, 0x8f, 0xa2, 0x03, 0x16, 0x8e, 0x0a,
	0x31, 0x89, 0xb3, 0x57, 0x61, 0x68, 0x7f, 0x0e, 0xe3, 0x35, 0x6c, 0x9f, 0x5e, 0xce, 0xe8, 0xa2,
	0xe8, 0x46, 0x45, 0xd4, 0xcb, 0xa3, 0x39, 0xfd, 0xb7, 0xbe, 0xef, 0x1a, 0x40, 0xf0, 0x29, 0x4d,
	0x8b, 0x20, 0x4b, 0x73, 0xca, 0x2f, 0x35, 0x2b, 0xa2, 0xbc, 0x08, 0xb3, 0x94, 0x5d, 0x89, 0x3e,
	0x9d, 0x98, 0xa2, 0x32, 0x4c, 0xd9, 0xd5, 0x0d, 0x78, 0x59, 0xbe, 0x4d, 0x15, 0xbc, 0x44, 0x7b,
	0xb0, 0x41, 0x17, 0xb1, 0xec, 0x95, 0xaf, 0x55, 0x93, 0x2e, 0x62, 0xd1, 0xb9, 0x82, 0x96, 0xe5,
	0xfb, 0x55, 0x42, 0x4b, 0xe7, 0x87, 0x0e, 0x9b, 0x52, 0xfb, 0x5f, 0x83, 0x97, 0x94, 0x1b, 0xc1,
	0xbf, 0x00, 0xa0, 0x51, 0xc1, 0x3d, 0xe3, 0x31, 0xc8, 0xfc, 0xb7, 0x65, 0x0c, 0x95, 0xd9, 0x44,
	0xa1, 0xa0, 0x0e, 0x58, 0x34, 0x2a, 0x44, 0x2c, 0xbc, 0xc3, 0x50, 0x83, 0x5b, 0x39, 0x4e, 0x54,
	0x12, 0x7a, 0x03, 0xdb, 0x1f, 0xc5, 0x6a, 0x9e, 0xe9, 0x05, 0x77, 0xb6, 0xbc, 0x1e, 0x3b, 0x8a,
	0xac, 0xca, 0x75, 0xb2, 0x4e, 0xe6, 0x22, 0x19, 0x37, 0x98, 0x71, 0x83, 0xcb, 0xbb, 0x22, 0x45,
	0xae, 0x7c, 0x27, 0x0a, 0xe5, 0xe4, 0xa7, 0x06, 0x96, 0x72, 0xcb, 0x91, 0x0d, 0x3b, 0x01, 0x26,
	0xe7, 0x98, 0xf8, 0xa4, 0x8b, 0x49, 0xe8, 0xb9, 0xc3, 0xb0, 0x3f, 0xe8, 0x8f, 0x5a, 0x77, 0xd0,
	0x3e, 0xdc, 0x5f, 0x47, 0xc6, 0xc3, 0xae, 0x3b, 0xc2, 0x2d, 0x6d, 0x1d, 0x2b, 0x3f, 0x55, 0x01,
	0x1e, 0xb5, 0x74, 0xf4, 0x00, 0x6c, 0x15, 0x93, 0xaf, 0x6d, 0xd9, 0x69, 0xac, 0xef, 0x7b, 0xe7,
	0x7a, 0xd8, 0x3f, 0xc7, 0xa4, 0x55, 0x3b, 0xf9, 0x06, 0x96, 0x92, 0x02, 0x27, 0x9e, 0x9e, 0xf5,
	0xf1, 0x60, 0x24, 0x89, 0xfc, 0x5b, 0x15, 0x62, 0x97, 0x0b, 0xdb, 0x83, 0x7b, 0x2a, 0x22, 0x17,
	0x70, 0x48, 0xe8, 0x52, 0xa1, 0xae, 0x3b, 0x72, 0xc3, 0x1e, 0x71, 0x3d, 0xdc, 0xd2, 0xd1, 0x01,
	0xec, 0xaa, 0x58, 0xf0, 0xde, 0xf7, 0x47, 0x61, 0x30, 0xf4, 0x09, 0x6e, 0x19, 0xd3, 0x86, 0xf8,
	0x67, 0x79, 0xf5, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x49, 0xb9, 0x05, 0xbc, 0x66, 0x06, 0x00, 0x00,
}
