// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package Msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//服务器消息-----------------------------------------
type ServerOrder int32

const (
	ServerOrder_SERVERORDER_MAP_INIT   ServerOrder = 0
	ServerOrder_SERVERORDER_MAP_UPDATE ServerOrder = 1
)

var ServerOrder_name = map[int32]string{
	0: "SERVERORDER_MAP_INIT",
	1: "SERVERORDER_MAP_UPDATE",
}

var ServerOrder_value = map[string]int32{
	"SERVERORDER_MAP_INIT":   0,
	"SERVERORDER_MAP_UPDATE": 1,
}

func (x ServerOrder) String() string {
	return proto.EnumName(ServerOrder_name, int32(x))
}

func (ServerOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type ClientOrder int32

const (
	ClientOrder_CLIENTORDER_FOOD_EAT ClientOrder = 0
)

var ClientOrder_name = map[int32]string{
	0: "CLIENTORDER_FOOD_EAT",
}

var ClientOrder_value = map[string]int32{
	"CLIENTORDER_FOOD_EAT": 0,
}

func (x ClientOrder) String() string {
	return proto.EnumName(ClientOrder_name, int32(x))
}

func (ClientOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

type Food struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PosX                 float32  `protobuf:"fixed32,2,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY                 float32  `protobuf:"fixed32,3,opt,name=posY,proto3" json:"posY,omitempty"`
	Bg                   float32  `protobuf:"fixed32,4,opt,name=bg,proto3" json:"bg,omitempty"`
	Size                 float32  `protobuf:"fixed32,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Food) Reset()         { *m = Food{} }
func (m *Food) String() string { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()    {}
func (*Food) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Food) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Food.Unmarshal(m, b)
}
func (m *Food) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Food.Marshal(b, m, deterministic)
}
func (m *Food) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Food.Merge(m, src)
}
func (m *Food) XXX_Size() int {
	return xxx_messageInfo_Food.Size(m)
}
func (m *Food) XXX_DiscardUnknown() {
	xxx_messageInfo_Food.DiscardUnknown(m)
}

var xxx_messageInfo_Food proto.InternalMessageInfo

func (m *Food) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Food) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *Food) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *Food) GetBg() float32 {
	if m != nil {
		return m.Bg
	}
	return 0
}

func (m *Food) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type MapInit struct {
	FOODS_NUM            int32    `protobuf:"varint,1,opt,name=FOODS_NUM,json=FOODSNUM,proto3" json:"FOODS_NUM,omitempty"`
	Food                 []*Food  `protobuf:"bytes,2,rep,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapInit) Reset()         { *m = MapInit{} }
func (m *MapInit) String() string { return proto.CompactTextString(m) }
func (*MapInit) ProtoMessage()    {}
func (*MapInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *MapInit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapInit.Unmarshal(m, b)
}
func (m *MapInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapInit.Marshal(b, m, deterministic)
}
func (m *MapInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapInit.Merge(m, src)
}
func (m *MapInit) XXX_Size() int {
	return xxx_messageInfo_MapInit.Size(m)
}
func (m *MapInit) XXX_DiscardUnknown() {
	xxx_messageInfo_MapInit.DiscardUnknown(m)
}

var xxx_messageInfo_MapInit proto.InternalMessageInfo

func (m *MapInit) GetFOODS_NUM() int32 {
	if m != nil {
		return m.FOODS_NUM
	}
	return 0
}

func (m *MapInit) GetFood() []*Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type Update struct {
	FoodId               int32    `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Food                 *Food    `protobuf:"bytes,2,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetFoodId() int32 {
	if m != nil {
		return m.FoodId
	}
	return 0
}

func (m *Update) GetFood() *Food {
	if m != nil {
		return m.Food
	}
	return nil
}

type ServerMessage struct {
	Order                ServerOrder `protobuf:"varint,1,opt,name=order,proto3,enum=Msg.ServerOrder" json:"order,omitempty"`
	Map                  *MapInit    `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	Update               *Update     `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetOrder() ServerOrder {
	if m != nil {
		return m.Order
	}
	return ServerOrder_SERVERORDER_MAP_INIT
}

func (m *ServerMessage) GetMap() *MapInit {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *ServerMessage) GetUpdate() *Update {
	if m != nil {
		return m.Update
	}
	return nil
}

type ClientMessage struct {
	Order                ClientOrder `protobuf:"varint,1,opt,name=order,proto3,enum=Msg.ClientOrder" json:"order,omitempty"`
	Food                 *Food       `protobuf:"bytes,2,opt,name=food,proto3" json:"food,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetOrder() ClientOrder {
	if m != nil {
		return m.Order
	}
	return ClientOrder_CLIENTORDER_FOOD_EAT
}

func (m *ClientMessage) GetFood() *Food {
	if m != nil {
		return m.Food
	}
	return nil
}

func init() {
	proto.RegisterEnum("Msg.ServerOrder", ServerOrder_name, ServerOrder_value)
	proto.RegisterEnum("Msg.ClientOrder", ClientOrder_name, ClientOrder_value)
	proto.RegisterType((*Food)(nil), "Msg.Food")
	proto.RegisterType((*MapInit)(nil), "Msg.MapInit")
	proto.RegisterType((*Update)(nil), "Msg.Update")
	proto.RegisterType((*ServerMessage)(nil), "Msg.ServerMessage")
	proto.RegisterType((*ClientMessage)(nil), "Msg.ClientMessage")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x6b, 0xab, 0x40,
	0x14, 0x8c, 0x1f, 0x31, 0x37, 0xc7, 0x9b, 0x20, 0xcb, 0xe5, 0x56, 0x5a, 0x5a, 0x82, 0x85, 0x36,
	0xe4, 0x21, 0x0f, 0xe9, 0x1f, 0x68, 0x48, 0x0c, 0x08, 0x55, 0xc3, 0x46, 0x43, 0xf3, 0x24, 0xca,
	0x6e, 0x45, 0x68, 0xb2, 0xe2, 0xda, 0x3e, 0x94, 0xfe, 0xf8, 0xb2, 0xab, 0x84, 0xb4, 0x94, 0xbc,
	0x1d, 0x67, 0xe6, 0xcc, 0xcc, 0x51, 0xa1, 0xbf, 0xe7, 0xf9, 0xb4, 0xac, 0x58, 0xcd, 0x90, 0xe6,
	0xf3, 0xdc, 0xc9, 0x40, 0x5f, 0x31, 0x46, 0xd0, 0x10, 0xd4, 0x82, 0xd8, 0xca, 0x48, 0x19, 0x77,
	0xb1, 0x5a, 0x10, 0x84, 0x40, 0x2f, 0x19, 0x7f, 0xb6, 0xd5, 0x91, 0x32, 0x56, 0xb1, 0x9c, 0x5b,
	0x6c, 0x67, 0x6b, 0x47, 0x6c, 0x27, 0xf6, 0xb2, 0xdc, 0xd6, 0x25, 0xa2, 0x66, 0xb9, 0xd0, 0xf0,
	0xe2, 0x83, 0xda, 0xdd, 0x46, 0x23, 0x66, 0xc7, 0x85, 0x9e, 0x9f, 0x96, 0xde, 0xa1, 0xa8, 0xd1,
	0x15, 0xf4, 0x57, 0x61, 0xb8, 0xdc, 0x24, 0x41, 0xec, 0xb7, 0x69, 0x7f, 0x24, 0x10, 0xc4, 0x3e,
	0xba, 0x06, 0xfd, 0x85, 0x31, 0x62, 0xab, 0x23, 0x6d, 0x6c, 0xce, 0xfa, 0x53, 0x9f, 0xe7, 0x53,
	0x51, 0x0e, 0x4b, 0xd8, 0x79, 0x04, 0x23, 0x2e, 0x49, 0x5a, 0x53, 0x74, 0x01, 0x3d, 0x81, 0x24,
	0xc7, 0xc6, 0x86, 0x78, 0xf4, 0xc8, 0x89, 0x83, 0xf2, 0x9b, 0xc3, 0x27, 0x0c, 0x36, 0xb4, 0x7a,
	0xa7, 0x95, 0x4f, 0x39, 0x4f, 0x73, 0x8a, 0xee, 0xa0, 0xcb, 0x2a, 0x42, 0x2b, 0x69, 0x33, 0x9c,
	0x59, 0x72, 0xa1, 0x91, 0x84, 0x02, 0xc7, 0x0d, 0x8d, 0x6e, 0x40, 0xdb, 0xa7, 0x65, 0x6b, 0xfb,
	0x57, 0xaa, 0xda, 0x8b, 0xb0, 0x20, 0xd0, 0x2d, 0x18, 0x6f, 0xb2, 0x9a, 0x7c, 0x37, 0xe6, 0xcc,
	0x94, 0x92, 0xa6, 0x2d, 0x6e, 0x29, 0x67, 0x0b, 0x83, 0xc5, 0x6b, 0x41, 0x0f, 0xf5, 0xd9, 0xf4,
	0x46, 0xf2, 0x2d, 0xfd, 0xfc, 0x55, 0x93, 0x05, 0x98, 0x27, 0x95, 0x91, 0x0d, 0xff, 0x36, 0x2e,
	0xde, 0xba, 0x38, 0xc4, 0x4b, 0x17, 0x27, 0xfe, 0x7c, 0x9d, 0x78, 0x81, 0x17, 0x59, 0x1d, 0x74,
	0x09, 0xff, 0x7f, 0x32, 0xf1, 0x7a, 0x39, 0x8f, 0x5c, 0x4b, 0x99, 0xdc, 0x83, 0x79, 0x92, 0x2c,
	0x4c, 0x16, 0x4f, 0x9e, 0x1b, 0x44, 0x8d, 0x54, 0x7c, 0xa2, 0xc4, 0x9d, 0x47, 0x56, 0x27, 0x33,
	0xe4, 0xcf, 0xf3, 0xf0, 0x15, 0x00, 0x00, 0xff, 0xff, 0x50, 0xe7, 0x0c, 0xc6, 0x49, 0x02, 0x00,
	0x00,
}
